#!/usr/bin/env python3

import os
import subprocess
import sys

scriptpath = os.path.dirname(os.path.realpath(__file__))

exe = os.path.join(scriptpath, "main.py")
command = 'conda run -n ZarrSeg %s' % exe
for item in sys.argv[1:]:
    command = command + ' ' + item

subprocess.run(command, shell = True)
