#!/usr/bin/env python3

# scriptpath = os.path.dirname(os.path.realpath(__file__))

import subprocess
import sys

command = 'conda run -n ZarrSeg main.py'
for item in sys.argv[1:]:
    command = command + ' ' + item

subprocess.run(command, shell = True)
